### ISSUE TITLE
Stuck after choosing color

### ISSUE THREAD

**Issue by yeatthedead** [FirePlank/Auto-Chess#10]
stuck after choosing my color without any error message
using python 3.9.0, installation went fine, no errors.
tried several different engines, wiped python multiple times and re-installed everything
happens on both lichess and chess.com, even using your recommended board settings

would appreciate any input

**Comment by FirePlank** [comment]
you need to try rezizing the board, make the board theme brown and white, i suggest looking at the troubleshooting section. Be aware that the ai was trained on the lichess board so ideally try lichess to see if anything is different or make the board bigger.

I would also recommend downgrading tensorflow to 2.5.0 since that's the version the ai was using when it was created.
